### ISSUE TITLE
El script que da EVs (en esta gen son Stat Experience) no calcula correctamente

### ISSUE THREAD

**Issue by Raguzero** [Raguzero/Midele-Crystal-v1.4b#9]
https://cdn.discordapp.com/attachments/430812825632374794/1089161657734926336/image.png
https://cdn.discordapp.com/attachments/430812825632374794/1089161787313762444/image.png

En este caso, Houndoom tiene 1 HP mas. El resto de stats parecen correctos. (tiene 13 DVs y maximo stat experience)

**Comment by Manectric-Rang** [comment]
Tampoco son correctos los demás stats; en 2ª gen cada punto adicional en un IV incrementa en 2 el stat (de forma que puede haber diferencia en hasta 30 puntos en cada stat, prácticamente como en generaciones posteriores).

Les pasa exactamente lo mismo: se le suma 64 al stat cuando debería ser 63.

**Comment by LavenderG** [comment]
Arreglado en fb769fc2abe0937acc4197b371af0003d53a372e
